---
- name: Create group 'local_adm'
  group:
    name: local_adm
    state: present
    system: yes
- name: Create group 'local_log'
  group:
    name: local_log
    state: present
    system: yes

- name: Add the user 'local_adm' with a specific uid and primary group of 'local_adm'
  user:
    name: local_adm
    shell: /bin/bash
    uid: 38000087
    home: /home/local_adm
    expires: -1
    group: local_adm
    append: no
    state: present

- name: Add the user 'local_log' with a specific uid and primary group of 'local_log'
  user:
    name: local_log
    shell: /bin/sh
    uid: 38000088
    expires: "{{ ('2023-12-31 23:59:59'|to_datetime).strftime('%s') }}"
    home: /home/local_log
    group: local_log
    append: no
    state: present


- name: Adding SSH key to authorized_keys
  ansible.posix.authorized_key:
    user: local_adm
    state: present
    key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"

- name: Adding SSH key to authorized_keys
  ansible.posix.authorized_key:
    user: local_log
    state: present
    key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
