---
    - name: Create group 'local_adm' 
      group:
        name: local_adm
        state: present
        system: yes 
    - name: Create group 'local_log' 
      group:
        name: local_adm
        state: present
        system: yes 
    
    - name: Add the user  'local_adm' with a specific uid and primary group of 'local_adm'
      user: 
        name: local_adm
        shell: /bin/bash
        uid: 38000087
        home: /home/local_adm
        expires: -1 
        groups: local_adm

    - name: Add the user 'local_log' with a specific uid and primary group of 'local_log'
      user:
        name: local_log
        shell: /bin/sh
        uid: 38000088
        expires: 2023-12-31
        home: /home/local_log
        groups: local_log

# tasks file for local_adm
