galaxy_info:
  author: Ammar123
  description: Ansible role to configure sshd service on Linux machine
  license: MIT
  version: "1.0.0"
  min_ansible_version: 2.12

  platforms:
   - name: RedHat
     versions:

     - 8
     - 9
  galaxy_tags:

    - system
    - users

