---
- name: Create users and group accounts with passworldess authentication and edit sshd service on target machines
  hosts: 192.168.198.130
  become: true 
  gather_facts: true
  tasks:

    - name: local_accounts role

      import_role:
        name: cloud.my_collection.local_accounts

    - name: ssh_config role

      import_role:
        name: cloud.my_collection.ssh_config
