---
- name: Creating local groups
  ansible.builtin.group:
     name: "{{ item.name }}"
     state: present
     system: "{{ item.system }}"
  loop: "{{ local_groups }}"

- name: Create local users
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /bin/bash
    uid: "{{ item.uid }}"
    home: /home/{{ item.name }}
    group: "{{ item.group }}"
    append: no
    state: present
    expires: "{{ item.expires }}"
  loop: "{{ local_users }}"

- name: Adding SSH key to authorized_keys
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', ssh_public_key_path) }}"
  loop: "{{ local_users }}"
