---
    - name: Set PasswordAuthentication to yes
      lineinfile:
        path: "{{ sshd_config_file }}"
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication yes"
        state: present
      when: not ansible_check_mode

    - name: Set PermitEmptyPasswords to no
      lineinfile:
        path: "{{ sshd_config_file }}"
        regexp: "^PermitEmptyPasswords"
        line: "PermitEmptyPasswords no"
        state: present
      when: not ansible_check_mode

    - name: Set PermitRootLogin to no
      lineinfile:
        path: "{{ sshd_config_file }}"
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
      when: not ansible_check_mode

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
      when: not ansible_check_mode


# tasks file for /home/ansible/cloud/roles/ssh_config
