---
- name: Create users with specific userid and specific primary groups
  hosts: 192.168.198.129
  become: true 
  gather_facts: true
  tasks:

    - name: local_accounts role

      import_role:
        name: cloud.my_collection.local_accounts



    - name: ssh_config role

      import_role:
        name: cloud.my_collection.ssh_config
